export const titleText = [
  'П',
  'р',
  'и',
  'в',
  'і',
  'т',
  '!<br />М',
  'е',
  'н',
  'е',
  ' ',
  'з',
  'в',
  'а',
  'т',
  'и',
  ' ',
  '<span class="vivid-red">Є</span>',
  '<span class="vivid-red">в</span>',
  '<span class="vivid-red">г</span>',
  '<span class="vivid-red">е</span>',
  '<span class="vivid-red">н</span>',
  '<br />Я',
  ' ',
  '-',
  ' ',
  '<span class="vivid-red">м</span>',
  '<span class="vivid-red">е</span>',
  '<span class="vivid-red">н</span>',
  '<span class="vivid-red">т</span>',
  '<span class="vivid-red">о</span>',
  '<span class="vivid-red">р</span>',
  window.innerWidth < 1200 ? '<br>з' : ' з',
  ' ',
  '<span class="vivid-red">в</span>',
  '<span class="vivid-red">е</span>',
  '<span class="vivid-red">б</span>',
  '<span class="vivid-red">-</span>',
  '<span class="vivid-red">р</span>',
  '<span class="vivid-red">о</span>',
  '<span class="vivid-red">з</span>',
  '<span class="vivid-red">р</span>',
  '<span class="vivid-red">о</span>',
  '<span class="vivid-red">б</span>',
  '<span class="vivid-red">к</span>',
  '<span class="vivid-red">и</span>',
];
